version: '3'

services:
  server:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8019:8019"
    external_links:
     - geoportal_psql:db
