version: 2.1

jobs:
  build-and-test:
    working_directory: ~/geoportal
    docker:
      - image: circleci/python:3.6.9
      - image: mdillon/postgis:11-alpine
        environment:
          POSTGRES_USER: geo
          POSTGRES_DB: geo_db
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            sudo apt-get update &&\
            sudo apt-get install -y gdal-bin python-gdal python3-gdal
            ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test