version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            ./manage.py test
            apt-get update && apt-get install -y \
            gdal-bin python-gdal python3-gdal
          name: Test

workflows:
  main:
    jobs:
      - build-and-test