version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: mdillon/postgis:11-alpine
      - image: osgeo/gdal:alpine-ultrasmall-latest

    environment:
      DATABASE_URL: postgis://postgres:@localhost/geo1
      DJANGO_SECRET_KEY: test
      DJANGO_READ_DOT_ENV_FILE: True
      DJANGO_SETTINGS_MODULE: geoportal.settings

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv geoenv
            . geoenv/bin/activate
            pip install -r requirements.txt
            sudo apt-get update &&\
            sudo apt-get install -y gdal-bin python-gdal python3-gdal

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "geoenv"
      - run:
          name: Running tests
          command: |
            . geoenv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app