version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: mdillon/postgis:11-alpine

    environment:
      DATABASE_URL: postgis://postgres:@localhost/geo
      DJANGO_SECRET_KEY: test
      DJANGO_READ_DOT_ENV_FILE: True
      DJANGO_SETTINGS_MODULE: geoportal.settings

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv geoenv
            . geoenv/bin/activate
            sudo apt-get update &&\
            sudo apt-get install -y binutils libproj-dev libgdal-dev gdal-bin gettext g++ gcc
            gdal-config --version
            pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "circle"
      - run:
          name: Running tests
          command: |
            . geoenv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app